## Basic Configuration

baseURL = 'https://staff42.org/'
builddrafts = false
canonifyurls = false
languageCode = "fr-FR"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Staff42 Community Bureau"
title = 'Staff42 Community Website'

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "" # Comment out to disable Disqus.
# googleAnalytics = ""
enableRobotsTXT = true

## Site Settings
[params]
author = "Staff42 Community Bureau"
description = "A French Staff-plus Engineering Community"
# intro = "Startup Guru Extraordinaire"
authorimage = "logo.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Staff42 Community Website"
keywords = "staff-plus,staff-engineering,community,engineers,french,francophone,france"

## Social Accounts
[params.social]
github = "staffeng42"
# instagram = "<username>"
# linkedin = "<username>"
# twitter = "<username>"
# facebook = "<username>"
# google = "<username>"
# stackoverflow = "<username>"
# email = "you@example.com"

## Extras
[params.extra]
copyright = "© 2016. Staff42 Community Bureau. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "join us"
    weight = 50
    identifier = "join"
    url = "/join/"
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "code de conduite"
    identifier = "code de conduite"
    weight = 200
    url = "/code_of_conduct/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 300
    url = "/about/"
