## Basic Configuration

baseURL = 'https://staff42.org/'
builddrafts = false
canonifyurls = false
languageCode = "fr-FR"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Staff42 Community Bureau"
title = 'Staff42 Community Website'

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "" # Comment out to disable Disqus.
# googleAnalytics = ""
enableRobotsTXT = true

## Site Settings
[params]
author = "Staff42 Community"
description = "La communauté des Staff Engineers Francophones"
# intro = "Startup Guru Extraordinaire"
authorimage = "logo.png"
dateformat = "Jan 22, 2024"

## Site Meta Settings
[params.meta]
description = "Staff42 site de la communauté"
keywords = "staff-plus,staff-engineering,community,engineers,french,francophone,france"

## Social Accounts
[params.social]
github = "staffeng42"
# instagram = "<username>"
# linkedin = "<username>"
# twitter = "<username>"
# facebook = "<username>"
# google = "<username>"
# stackoverflow = "<username>"
# email = "you@example.com"

## Extras
[params.extra]
copyright = "©2024 by Staff42 Bureau is licensed under [CC BY-NC-ND 4.0](http://creativecommons.org/licenses/by-nc-nd/4.0/?ref=chooser-v1)"
poweredby = false
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "Qu'est-ce que Staff42 ?"
    identifier = "about"
    weight = 10
    url = "/about/"
[[menu.main]]
    name = "Nous rejoindre"
    weight = 50
    identifier = "join"
    url = "/join/"
[[menu.main]]
    name = "Blog et informations"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "Code de conduite"
    identifier = "code de conduite"
    weight = 200
    url = "/code_of_conduct/"

